# Generated by Django 6.0.6 on 2026-06-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_architecture', models.TextField()),
                ('runtime_vectors', models.CharField(blank=True, max_length=255, null=True)),
                ('blueprint', models.TextField()),
                ('source_code', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
